/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class UTS_11140367_Tampil_Kalkulator extends javax.swing.JFrame {
    private double total1 = 0.;
    private double total2 = 0;
    private char math_operator;
    
  
    public UTS_11140367_Tampil_Kalkulator() {
        initComponents();
    }
private void getOperator(String btnText){
         math_operator = btnText.charAt(0);
         total1 = total1 + Double.parseDouble(display.getText());
        display.setText("");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display = new javax.swing.JTextField();
        BtnAngka1 = new javax.swing.JButton();
        BtnAngka2 = new javax.swing.JButton();
        BtnAngka3 = new javax.swing.JButton();
        BtnAngka4 = new javax.swing.JButton();
        BtnAngka5 = new javax.swing.JButton();
        BtnAngka6 = new javax.swing.JButton();
        BtnAngka7 = new javax.swing.JButton();
        BtnAngka8 = new javax.swing.JButton();
        BtnAngka9 = new javax.swing.JButton();
        BtnAngka0 = new javax.swing.JButton();
        BtnKoma = new javax.swing.JButton();
        BtnC = new javax.swing.JButton();
        BtnTambah = new javax.swing.JButton();
        BtnKurang = new javax.swing.JButton();
        BtnKali = new javax.swing.JButton();
        BtnBagi = new javax.swing.JButton();
        BtnTambahKurang = new javax.swing.JButton();
        BtnSamaDengan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 11, 282, 47));

        BtnAngka1.setText("1");
        BtnAngka1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka1ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAngka1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 69, 65, -1));

        BtnAngka2.setText("2");
        BtnAngka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka2ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAngka2, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 69, 65, -1));

        BtnAngka3.setText("3");
        BtnAngka3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka3ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAngka3, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 69, 65, -1));

        BtnAngka4.setText("4");
        BtnAngka4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka4ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAngka4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 103, 65, -1));

        BtnAngka5.setText("5");
        BtnAngka5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka5ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAngka5, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 103, 65, -1));

        BtnAngka6.setText("6");
        BtnAngka6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka6ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAngka6, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 103, 65, -1));

        BtnAngka7.setText("7");
        BtnAngka7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka7ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAngka7, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 137, 65, -1));

        BtnAngka8.setText("8");
        BtnAngka8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka8ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAngka8, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 137, 65, -1));

        BtnAngka9.setText("9");
        BtnAngka9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka9ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAngka9, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 137, 65, -1));

        BtnAngka0.setText("0");
        BtnAngka0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka0ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAngka0, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 171, 65, -1));

        BtnKoma.setText(".");
        BtnKoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKomaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnKoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 171, 65, -1));

        BtnC.setText("C");
        BtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCActionPerformed(evt);
            }
        });
        getContentPane().add(BtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 171, 65, -1));

        BtnTambah.setText("+");
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(BtnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 69, 65, -1));

        BtnKurang.setText("-");
        BtnKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKurangActionPerformed(evt);
            }
        });
        getContentPane().add(BtnKurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 103, 65, -1));

        BtnKali.setText("*");
        BtnKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKaliActionPerformed(evt);
            }
        });
        getContentPane().add(BtnKali, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 137, 65, -1));

        BtnBagi.setText("/");
        BtnBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBagiActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 171, 65, -1));

        BtnTambahKurang.setText("+/-");
        BtnTambahKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahKurangActionPerformed(evt);
            }
        });
        getContentPane().add(BtnTambahKurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 205, 136, -1));

        BtnSamaDengan.setText("=");
        BtnSamaDengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSamaDenganActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSamaDengan, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 205, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAngka1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka1ActionPerformed
        String BtnAngka1Text = display.getText() + BtnAngka1.getText();
        display.setText(BtnAngka1Text);
    }//GEN-LAST:event_BtnAngka1ActionPerformed

    private void BtnAngka2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka2ActionPerformed
        String BtnAngka2Text = display.getText() + BtnAngka2.getText();
        display.setText(BtnAngka2Text);
    }//GEN-LAST:event_BtnAngka2ActionPerformed

    private void BtnAngka3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka3ActionPerformed
        String BtnAngka3Text = display.getText() + BtnAngka3.getText();
        display.setText(BtnAngka3Text);
    }//GEN-LAST:event_BtnAngka3ActionPerformed

    private void BtnAngka4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka4ActionPerformed
        String BtnAngka4Text = display.getText() + BtnAngka4.getText();
        display.setText(BtnAngka4Text);
    }//GEN-LAST:event_BtnAngka4ActionPerformed

    private void BtnAngka5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka5ActionPerformed
        String BtnAngka5Text = display.getText() + BtnAngka5.getText();
        display.setText(BtnAngka5Text);
    }//GEN-LAST:event_BtnAngka5ActionPerformed

    private void BtnAngka6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka6ActionPerformed
        String BtnAngka6Text = display.getText() + BtnAngka6.getText();
        display.setText(BtnAngka6Text);
    }//GEN-LAST:event_BtnAngka6ActionPerformed

    private void BtnAngka7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka7ActionPerformed
        String BtnAngka7Text = display.getText() + BtnAngka7.getText();
        display.setText(BtnAngka7Text);
    }//GEN-LAST:event_BtnAngka7ActionPerformed

    private void BtnAngka8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka8ActionPerformed
        String BtnAngka8Text = display.getText() + BtnAngka8.getText();
        display.setText(BtnAngka8Text);
    }//GEN-LAST:event_BtnAngka8ActionPerformed

    private void BtnAngka9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka9ActionPerformed
        String BtnAngka9Text = display.getText() + BtnAngka9.getText();
        display.setText(BtnAngka9Text);
    }//GEN-LAST:event_BtnAngka9ActionPerformed

    private void BtnAngka0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka0ActionPerformed
        String BtnAngka0Text = display.getText() + BtnAngka0.getText();
        display.setText(BtnAngka0Text);
    }//GEN-LAST:event_BtnAngka0ActionPerformed

    private void BtnKomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKomaActionPerformed
        String BtnKomaText = display.getText() + BtnKoma.getText();
        display.setText(BtnKomaText);
    }//GEN-LAST:event_BtnKomaActionPerformed

    private void BtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCActionPerformed
        total2 = 0;
        display.setText("");
    }//GEN-LAST:event_BtnCActionPerformed

    private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahActionPerformed
        String button_text = BtnTambah.getText();
        getOperator(button_text); 

    }//GEN-LAST:event_BtnTambahActionPerformed

    private void BtnKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKurangActionPerformed
        String button_text = BtnKurang.getText();
        getOperator(button_text); 

    }//GEN-LAST:event_BtnKurangActionPerformed

    private void BtnKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKaliActionPerformed
        String button_text = BtnKali.getText();
        getOperator(button_text); 

    }//GEN-LAST:event_BtnKaliActionPerformed

    private void BtnBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBagiActionPerformed
        String button_text = BtnBagi.getText();
        getOperator(button_text); 

    }//GEN-LAST:event_BtnBagiActionPerformed

    private void BtnSamaDenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSamaDenganActionPerformed
        switch (math_operator){
            case '+':
            total2 = total1 + Double.parseDouble(display.getText( ) );
            break;
            case '-':
            total2 = total1 - Double.parseDouble(display.getText( ) );
            break;
            case '*':
            total2 = total1 * Double.parseDouble(display.getText( ) );
            break;
            case '/':
            total2 = total1 / Double.parseDouble(display.getText( ) );
            break;
        }
        display.setText( Double.toString(total2) );
        total1 = 0;
    }//GEN-LAST:event_BtnSamaDenganActionPerformed

    private void BtnTambahKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahKurangActionPerformed
        String button_text = BtnTambahKurang.getText();
        getOperator(button_text); 
        
    }//GEN-LAST:event_BtnTambahKurangActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UTS_11140367_Tampil_Kalkulator().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAngka0;
    private javax.swing.JButton BtnAngka1;
    private javax.swing.JButton BtnAngka2;
    private javax.swing.JButton BtnAngka3;
    private javax.swing.JButton BtnAngka4;
    private javax.swing.JButton BtnAngka5;
    private javax.swing.JButton BtnAngka6;
    private javax.swing.JButton BtnAngka7;
    private javax.swing.JButton BtnAngka8;
    private javax.swing.JButton BtnAngka9;
    private javax.swing.JButton BtnBagi;
    private javax.swing.JButton BtnC;
    private javax.swing.JButton BtnKali;
    private javax.swing.JButton BtnKoma;
    private javax.swing.JButton BtnKurang;
    private javax.swing.JButton BtnSamaDengan;
    private javax.swing.JButton BtnTambah;
    private javax.swing.JButton BtnTambahKurang;
    private javax.swing.JTextField display;
    // End of variables declaration//GEN-END:variables
}
